### ISSUE TITLE
Release v0.9

### ISSUE THREAD

**Issue by stevesloka** [fermyon/spin-containerd-shim-installer#7]
Hey @jpflueger curious if a new release to v0.9 would allow Spin 1.5 apps to work with the Shim? I tried upgrading with the current latest version and it didn't work for me. 

If this does fix, would you be able to cut a new tag and a new release?

**Comment by jpflueger** [comment]
Hey @stevesloka! There is currently an [issue](https://github.com/deislabs/containerd-wasm-shims/issues/123) with the v0.9 release of the shim currently doesn't pass through stdout correctly which means no `kubectl logs ...`. I can make a branch with the v0.9 shim for you to test out if you wanted to see if the issue effects you?

**Comment by jpflueger** [comment]
Hey @stevesloka, there are now releases for versions 0.9.0, 0.9.1, 0.9.2, and 0.10.0. I've tested them and they work for me but let me know if you find issues. I have pushed a tag for 0.9.3 but it seems like the github action isn't running so I'll try and get that release going here this week. Let me know if these work for you and I'll close out the issue.
